export const DVNutrition = {
  Fat: 65,
  SaturatedFat: 20,
  Cholesterol: 300,
  Sodium: 3500,
  Carbohydrates: 300,
  Potassium: 3500,
  DiateryFiber: 25,
  VitaminA: 5000,
  VitaminC: 60,
  Calcium: 1100,
  Iron: 18,
}

export const listAttr = [
  'Calories',
  'Fat',
  'TransFat',
  'SaturatedFat',
  'Protein',
  'Cholesterol',
  'Sodium',
  'Potassium',
  'Carbohydrates',
  'DiateryFiber',
  'Sugars',
  'VitaminA',
  'VitaminC',
  'Calcium',
  'Iron',
]